# Generated by Django 4.0.5 on 2022-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompyuter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompyuter',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
